### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#18]
The site is having some considerable trouble with Safari. Could you guys have a closer look at this? I'm only seeing the last 5 projects in the list of 20, and when i click on a project it also just loads the very bottom of the page. It seems not to affect the iOS version of Safari tho, when I look at it on my phone.

**Comment by feeohnah** [comment]
@cartogram Confirmed. This seems to be something that occurs in Desktop Safari 10.1+, there's something preventing the ability to scroll and it starts you at the bottom. On v9.1 everything works fine.

I think it's related to the ```display: flex;``` property because when I remove that, I regain the ability to scroll. Is it just a matter of adding the appropriate prefixing?

**Comment by feeohnah** [comment]
@MattSelf this should be resolved now, can you confirm on your end?

**Comment by MattSelf** [comment]
Yes it seems fixed. It doesn't start at the bottom anymore, but the homepage is still just a single column of images.

**Comment by feeohnah** [comment]
@MattSelf okay I think that aspect is un-related to the browser and is related to the global grid issues: https://github.com/studio-cartogram/studioself/issues/21
